- branchNamePattern: "(feature|bugfix|hotfix)/.*"
  environment: "PREDEV"
- branchNamePattern: "master"
  environment: "BUILD"
- branchNamePattern: "develop"
  environment: "DEV"
- branchNamePattern: "staging"
  environment: "STAGING"
- branchNamePattern: "production"
  environment: "PROD"
